Update bitflags dependency
Limiting bitflags to <2.1.0 causes compatibility issues and build
failures with other crates, e.g:

error: failed to select a version for `bitflags`.
    ... required by package `bindgen v0.68.1`
    ... which satisfies dependency `bindgen = "^0.68.1"` of package ...
versions that meet the requirements `^2.2.1` are: 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.1

all possible versions conflict with previously selected packages.

  previously selected package `bitflags v2.0.2`
    ... which satisfies dependency `bitflags = ">=1.3.1, <2.1.0"` (locked to 2.0.2) of package `serialport v4.2.2`
    ... which satisfies dependency `serialport = "^4.2.2"` (locked to 4.2.2) of package ...

failed to select a version for `bitflags` which could resolve this conflict